### ISSUE TITLE
Any news about 0.15 compatibility?

### ISSUE THREAD

**Issue by xenadmin** [jpas/factorio-expanded-tools#4]
Just out of couriosity, as I like this mod very much.

**Comment by jpas** [comment]
I'll do it this weekend.

 I just need to figure out the new recipe/tech to replace the 10x Alien Artifacts in the Atomic Disassembler, maybe 10x Uranium-238?

**Comment by jpas** [comment]
Unlocking with Nuclear Power, of course.

**Comment by xenadmin** [comment]
Looking forward to it. It should be of course be a product from the new nuclear tech tree. And The one Uranium that is rare sound reasonable. 
Alternative 100x from the one that's not rare?
Thank you so much for your work and this great mod!

**Comment by jpas** [comment]
I have added to the releases page. mods.factorio.com isn't loading properly for me right now but I'll put the release up there as soon as I can.

**Comment by jpas** [comment]
I have uploaded it to mods.factorio.com now, you should be able to update through the client.
